# Generated by Django 5.2.1 on 2025-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(verbose_name='Код валюты')),
                ('rate', models.FloatField(verbose_name='Курс валюты к RUB')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
